"""The data-access interface. Rows are plain dicts whose keys match the SQL columns.

Two implementations:
  * SupabaseRepository  (app/db/supabase_repo.py) - production, Postgres via Supabase.
  * LocalRepository     (app/db/local_repo.py)    - local demo mode / tests, a JSON file.

Ownership rule used by the API layer: every notebook has a user_id; everything
else (sources, chunks, generations, chat) belongs to a notebook. The API checks
`get_notebook(user_id, notebook_id)` before touching a notebook's children.
"""

from typing import Any, Protocol

Row = dict[str, Any]

SOURCE_STATUSES = ("uploaded", "extracting", "chunking", "embedding", "ready", "failed")


class Repository(Protocol):
    # profiles
    def ensure_profile(self, user_id: str, email: str | None) -> None: ...

    # notebooks
    def create_notebook(self, user_id: str, title: str, description: str | None) -> Row: ...
    def list_notebooks(self, user_id: str) -> list[Row]: ...
    def get_notebook(self, user_id: str, notebook_id: str) -> Row | None: ...
    def update_notebook(self, notebook_id: str, fields: Row) -> Row: ...
    def delete_notebook(self, notebook_id: str) -> None: ...
    def bump_sources_version(self, notebook_id: str) -> int: ...

    # sources
    def create_source(self, row: Row) -> Row: ...
    def get_source(self, source_id: str) -> Row | None: ...
    def list_sources(self, notebook_id: str) -> list[Row]: ...
    def find_source_by_hash(self, notebook_id: str, content_hash: str) -> Row | None: ...
    def update_source(self, source_id: str, fields: Row) -> Row: ...
    def delete_source(self, source_id: str) -> None: ...

    # chunks
    def replace_chunks(self, source_id: str, rows: list[Row]) -> None: ...
    def list_chunks(self, notebook_id: str, source_ids: list[str] | None = None) -> list[Row]: ...
    def get_chunks(self, chunk_ids: list[str]) -> list[Row]: ...

    # generations
    def find_generation(self, notebook_id: str, pipeline_name: str, params_hash: str, sources_version: int) -> Row | None: ...
    def save_generation(self, row: Row) -> Row: ...
    def list_generations(self, notebook_id: str, limit: int = 50) -> list[Row]: ...
    def get_generation(self, generation_id: str) -> Row | None: ...

    # chat
    def create_chat_session(self, row: Row) -> Row: ...
    def get_chat_session(self, session_id: str) -> Row | None: ...
    def list_chat_sessions(self, notebook_id: str) -> list[Row]: ...
    def touch_chat_session(self, session_id: str) -> None: ...
    def delete_chat_session(self, session_id: str) -> None: ...
    def add_chat_message(self, row: Row) -> Row: ...
    def list_chat_messages(self, session_id: str, limit: int | None = None) -> list[Row]: ...


class FileStorage(Protocol):
    """Where original uploaded files live (Supabase Storage or a local folder)."""

    def put(self, path: str, data: bytes, content_type: str) -> None: ...
    def get(self, path: str) -> bytes: ...
    def delete(self, paths: list[str]) -> None: ...
