import PublicPage from '../../landing/PublicPage'
import { API_URL } from '../../lib/api'

// The REST API in plain words. The interactive reference (every field, try-it-out) is
// generated by the server itself at /docs, so this page explains and links rather than duplicates.
const GROUPS = [
  {
    title: 'Notebooks',
    rows: [
      ['GET', '/notebooks', 'Your notebooks, newest first, with document counts'],
      ['POST', '/notebooks', 'Create a notebook: title and optional description'],
      ['GET', '/notebooks/{id}', 'One notebook'],
      ['PATCH', '/notebooks/{id}', 'Rename or change the description'],
      ['DELETE', '/notebooks/{id}', 'Delete it and everything in it'],
    ],
  },
  {
    title: 'Documents',
    rows: [
      ['POST', '/notebooks/{id}/sources', 'Upload a file (PDF, DOCX, TXT, MD, image or audio). Processing starts in the background'],
      ['POST', '/notebooks/{id}/sources/text', 'Add pasted text as a document'],
      ['GET', '/notebooks/{id}/sources', 'The documents in a notebook with their status'],
      ['GET', '/sources/{id}', 'One document; poll this until its status is ready or failed'],
      ['GET', '/sources/{id}/chunks', 'The passages a document was split into, with page and heading'],
      ['POST', '/sources/{id}/retry', 'Process a failed document again'],
      ['DELETE', '/sources/{id}', 'Remove a document and its passages'],
    ],
  },
  {
    title: 'Study formats',
    rows: [
      ['GET', '/pipelines', 'The sixteen formats with their descriptions'],
      ['POST', '/notebooks/{id}/generate/{format}', 'Make a format from the notebook. Body: difficulty, length, focus_topic, source_ids, force'],
      ['GET', '/notebooks/{id}/generations', 'Everything made earlier in this notebook'],
      ['POST', '/notebooks/{id}/search', 'Run the search step on its own and see what every layer returned'],
    ],
  },
  {
    title: 'Chat',
    rows: [
      ['POST', '/notebooks/{id}/chat', 'Ask a question. The answer streams back as server-sent events with citations'],
      ['GET', '/notebooks/{id}/chat/sessions', 'Past conversations in a notebook'],
      ['GET', '/chat/sessions/{id}/messages', 'The messages of one conversation, with their citations'],
      ['DELETE', '/chat/sessions/{id}', 'Delete a conversation'],
    ],
  },
  {
    title: 'Service',
    rows: [['GET', '/health', 'Whether the server is up, which models are configured and which embedding model actually ran']],
  },
]

export default function ApiPage({ signedIn }) {
  return (
    <PublicPage
      signedIn={signedIn}
      wide
      title="API reference"
      lede="Everything the interface does, it does through this API, so anything you can click you can also script."
    >
      <section className="public-section">
        <h2>The basics</h2>
        <p>
          Requests carry your sign-in token as <code>Authorization: Bearer …</code>. Errors come back as JSON with a{' '}
          <code>detail</code> field and a meaningful status: 401 for a bad token, 404 for anything that is not yours,
          409 when a notebook has no processed documents yet, 413 for a file that is too large, 503 when the AI service
          is unavailable.
        </p>
        <p className="row" style={{ gap: 'var(--space-3)', flexWrap: 'wrap' }}>
          <a href={`${API_URL}/docs`} target="_blank" rel="noreferrer" className="btn btn-primary">
            Open the interactive reference
          </a>
          <a
            href="https://github.com/Lukey-7/StudyForge/blob/v2/docs/API.md"
            target="_blank"
            rel="noreferrer"
            className="btn btn-secondary"
          >
            Full contract on GitHub
          </a>
        </p>
        <p className="public-note">
          The interactive reference is served by the API itself ({API_URL}) and lets you try every call.
        </p>
      </section>

      {GROUPS.map((group) => (
        <section key={group.title} className="public-section">
          <h2>{group.title}</h2>
          <div className="table-scroll">
            <table className="data-table api-table">
              <thead>
                <tr>
                  <th>Method</th>
                  <th>Path</th>
                  <th>What it does</th>
                </tr>
              </thead>
              <tbody>
                {group.rows.map(([method, path, what]) => (
                  <tr key={method + path}>
                    <td>
                      <code>{method}</code>
                    </td>
                    <td>
                      <code>{path}</code>
                    </td>
                    <td>{what}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      ))}
    </PublicPage>
  )
}
